--
-- PostgreSQL database dump
--

-- Dumped from database version 12.3
-- Dumped by pg_dump version 12.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: appdea; Type: TABLE; Schema: public; Owner: Koko
--

CREATE TABLE public.appdea (
    id integer NOT NULL,
    name character varying NOT NULL,
    description character varying(540) NOT NULL
);


ALTER TABLE public.appdea OWNER TO "Koko";

--
-- Name: appdea_id_seq; Type: SEQUENCE; Schema: public; Owner: Koko
--

CREATE SEQUENCE public.appdea_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.appdea_id_seq OWNER TO "Koko";

--
-- Name: appdea_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: Koko
--

ALTER SEQUENCE public.appdea_id_seq OWNED BY public.appdea.id;


--
-- Name: appdea id; Type: DEFAULT; Schema: public; Owner: Koko
--

ALTER TABLE ONLY public.appdea ALTER COLUMN id SET DEFAULT nextval('public.appdea_id_seq'::regclass);


--
-- Data for Name: appdea; Type: TABLE DATA; Schema: public; Owner: Koko
--

COPY public.appdea (id, name, description) FROM stdin;
1	myfirst app	my very first app
2	My new app	My new app in TypeScript
3	My new app	My new app in TypeScript
4	My new app	My new app in TypeScript
5	My new app	My new app in TypeScript
6	My new app	My new app in TypeScript
7	My new app	My new app in TypeScript
\.


--
-- Name: appdea_id_seq; Type: SEQUENCE SET; Schema: public; Owner: Koko
--

SELECT pg_catalog.setval('public.appdea_id_seq', 8, true);


--
-- Name: appdea appdea_pkey; Type: CONSTRAINT; Schema: public; Owner: Koko
--

ALTER TABLE ONLY public.appdea
    ADD CONSTRAINT appdea_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

