"""empty message

Revision ID: dd22e25a6232
Revises: f36d0b3a351f
Create Date: 2020-08-07 16:46:22.611311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd22e25a6232'
down_revision = 'f36d0b3a351f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appdea', 'name2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appdea', sa.Column('name2', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
